[buildPlans.IosevkeleyMono]
family = "Iosevkeley Mono"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkeleyMono.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-serifless"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-inward-serifed-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
c = "bilateral-inward-serifed"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-serifless"
h = "straight-serifless"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck2"
u = "toothed-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
lower-theta = "cursive"
lower-lambda = "straight"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-open"
ampersand = "closed"
at = "fourfold"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "dots"
bar = "natural-slope"
question = "corner"
pilcrow = "high"
micro-sign = "toothed-serifless"
decorative-angle-brackets = "middle"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkeleyMono.variants.italic]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-serifless"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-inward-serifed-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
c = "bilateral-inward-serifed"
d = "toothed-serifless"
e = "rounded"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-serifless"
h = "straight-serifless"
i = "serifed-semi-tailed"
j = "flat-hook-serifed"
k = "cursive-serifless"
l = "serifed-semi-tailed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck2"
u = "toothed-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
lower-theta = "cursive"
lower-lambda = "straight"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-open"
ampersand = "closed"
at = "fourfold"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "dots"
bar = "natural-slope"
question = "corner"
pilcrow = "high"
micro-sign = "toothed-serifless"
decorative-angle-brackets = "middle"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkeleyMono.variants.oblique]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-serifless"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-inward-serifed-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
c = "bilateral-inward-serifed"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-serifless"
h = "straight-serifless"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck2"
u = "toothed-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
lower-theta = "cursive"
lower-lambda = "straight"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-open"
ampersand = "closed"
at = "fourfold"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "dots"
bar = "natural-slope"
question = "corner"
pilcrow = "high"
micro-sign = "toothed-serifless"
decorative-angle-brackets = "middle"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkeleyMono.ligations]
  inherits = "dlig"

[buildPlans.IosevkeleyMono.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkeleyMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkeleyMono.widths.Extended]
shape = 720
menu = 7
css = "expanded"
