#    ┓┏┓┳┏┳┓┏┳┓┓┏
#    ┃┫ ┃ ┃  ┃ ┗┫
#    ┛┗┛┻ ┻  ┻ ┗┛
#

# Fonts
font_family      family='JetBrains Mono'
bold_font        auto
italic_font      family='Ubuntu Mono' style='Regular'
bold_italic_font family='Ubuntu Mono' style='Bold'
font_size        12.0

# Padding
window_margin_width 20

# Use bash shell
shell bash

# Shell integration
shell_integration  no-title no-cursor

# Cursor
cursor_shape block
cursor_trail 1
cursor_blink_interval -1 linear ease-in-out

# No stupid close confirmation
confirm_os_window_close 0

# No stupid window alert on bell
window_alert_on_bell no

# Copy
map ctrl+c    copy_or_interrupt

# Search
map kitty_mod+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll & Zoom
map page_up                        scroll_page_up
map page_down                      scroll_page_down
map ctrl+plus                      change_font_size all +1
map ctrl+minus                     change_font_size all -1
map ctrl+0 change_font_size all    0

# Tab bar
tab_bar_edge top
tab_bar_style powerline
tab_activity_symbol " "
tab_powerline_style slanted
tab_title_template "{fmt.fg.color9}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index}:{tab.active_exe}"

# Theme
include everforest.conf
