#    ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓
#    ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃
#    ┗┛ ┻ ┛┗┛┗┗┛┛┗┻┣┛
#                    

# A Simple yet elegant starship config
# Created by BUGS

# Schema
"$schema" = 'https://starship.rs/config-schema.json'

# Options
add_newline = true
command_timeout = 200

# Prompt format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$jobs
$character"""

# Character
[character]
error_symbol = "[❯](bright-red)"
success_symbol = "[❯](bright-green)"
vimcmd_symbol = "[❮](bright-green)"
vimcmd_visual_symbol = "[❮](bright-cyan)"
vimcmd_replace_symbol = "[❮](bright-yellow)"
vimcmd_replace_one_symbol = "[❮](bright-yellow)"

# Directory
[directory]
style = 'bright-blue'
read_only_style = 'bright-red'
home_symbol = 'home'
read_only = ' '
truncation_length = 2
truncation_symbol = '…/'
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style) '
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

# Git branch
[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

# Git status
[git_status]
stashed = "≡"
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold bright-red"

# Git state
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

# Cmd duration
[cmd_duration]
format = "[$duration]($style) "
style = "bright-yellow"

# Background jobs
[jobs]
symbol = '✦'
style = 'bright-purple'
format = '[$symbol$number]($style)'
