# ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓
# ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃
# ┗┛ ┻ ┛┗┛┗┗┛┛┗┻┣┛
#
# A Simple yet elegant starship config
# Created by BUGS

# Schema
"$schema" = 'https://starship.rs/config-schema.json'

# Options
add_newline = true
command_timeout = 200

# Prompt format
format = """
$username\
$hostname\
$sudo\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$jobs
$character"""

# Character
[character]
error_symbol = "[→](bold bright-red)"
success_symbol = "[→](bold bright-green)"
vimcmd_symbol = "[←](bold bright-green)"
vimcmd_visual_symbol = "[←](bold bright-cyan)"
vimcmd_replace_symbol = "[←](bold bright-yellow)"
vimcmd_replace_one_symbol = "[←](bold bright-yellow)"

# Cmd duration
[cmd_duration]
format = "[󱦟 $duration]($style) "
style = "yellow"

# Directory
[directory]
style = 'blue'
read_only_style = 'red'
home_symbol = 'home'
read_only = ' '
truncation_length = 2
truncation_symbol = '…/'
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style) '
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

# Git branch
[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "cyan"

# Git metrics
[git_metrics]
disabled = false
added_style = 'green'
deleted_style = 'red'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) ) '

# Git state
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

# Git status
[git_status]
stashed = "≡"
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"

# Background jobs
[jobs]
symbol = ' '
style = 'purple'
format = '[$symbol$number]($style) '

# Sudo
[sudo]
disabled = false
style = "bold red"
symbol = " "
format = '[$symbol]($style)'
