#    ┏┳┓┓┏┏┓┳┳┓┏┓
#     ┃ ┣┫┣ ┃┃┃┣
#     ┻ ┛┗┗┛┛ ┗┗┛
#

# Schema
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Flavour
[flavor]
dark  = ""
light = ""

# App
[app]
overall = {}

# Manager
[mgr]
cwd = { fg = "#f38c61", italic = true, bold = true }

# Find
find_keyword  = { fg = "#d282d9", bg = "#d95762", bold = true }
find_position = { fg = "#92e2f2", bg = "#1c2021", bold = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "#a6d98d", bg = "#a6d98d" }
marker_cut      = { fg = "#e65c68", bg = "#e65c68" }
marker_marked   = { fg = "#d282d9", bg = "#d282d9" }
marker_selected = { fg = "#f38c61", bg = "#f38c61" }

# Count
count_copied   = { fg = "#d282d9", bg = "#a6d98d" }
count_cut      = { fg = "#d282d9", bg = "#e65c68" }
count_selected = { fg = "#d282d9", bg = "#9ec1f3" }

# Border
border_symbol = "│"
border_style  = { fg = "#98eeff" }

# Tabs
[tabs]
active   = { fg = "#d282d9", bg = "#9ec1f3", bold = true }
inactive = { fg = "#9ec1f3", bg = "#2c3334" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# Mode
[mode]
normal_main = { fg = "#e2e5e6", bg = "#9ec1f3", bold = true }
normal_alt  = { fg = "#9ec1f3", bg = "#2c3334" }
select_main = { fg = "#e2e5e6", bg = "#d282d9", bold = true }
select_alt  = { fg = "#e2e5e6", bg = "#2c3334" }
unset_main  = { fg = "#d282d9", bg = "#9ec1f3", bold = true }
unset_alt   = { fg = "#9ec1f3", bg = "#2c3334" }

# Indicator
[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "█", close = "█" }

# Status bar
[status]
overall   = { fg = "#e2e5e6", bg = "#1c2021" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#e2e5e6", bold = true }
progress_normal = { fg = "#95b7e6", bg = "#1c2021" }
progress_error  = { fg = "#d95762", bg = "#1c2021" }

# Permissions
perm_type  = { fg = "#9ec1f3" }
perm_read  = { fg = "#f38c61" }
perm_write = { fg = "#e65c68" }
perm_exec  = { fg = "#a6d98d" }
perm_sep   = { fg = "#414c4d" }


# Which
[which]
cols            = 3
mask            = { bg = "#1c2021" }
cand            = { fg = "#9ec1f3" }
rest            = { fg = "#9ec1f3" }
desc            = { fg = "#9ec1f3" }
separator       = " 󰶻  "
separator_style = { fg = "#d282d9" }

# Confirm
[confirm]
border  = { fg = "#95b7e6" }
title   = { fg = "#95b7e6" }
content = {}
list    = {}
btn_yes = { bg = "#a6d98d", fg = "#101314" }
btn_no  = { bg = "#d95762", fg = "#101314" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#95b7e6" }
title   = { fg = "#95b7e6" }

tbl_col  = { fg = "#9ec1f3" }
tbl_cell = { fg = "#f38c61", bg = "#1c2021" }

# Notify
[notify]
title_info  = { fg = "#92e2f2" }
title_warn  = { fg = "#f38c61" }
title_error = { fg = "#d95762" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

# Picker
[pick]
border   = { fg = "#95b7e6" }
active   = { fg = "#e2e5e6", bg = "#2c3334" }
inactive = { fg = "#e2e5e6" }

# Input
[input]
border   = { fg = "#a6d98d" }
title    = { fg = "#a6d98d" }
value    = { fg = "#9ec1f3" }
selected = { bg = "#2c3334" }

# Completion
[cmp]
border   = { fg = "#a6d98d" }
active   = { fg = "#e2e5e6", bg = "#2c3334" }
inactive = { fg = "#e2e5e6" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#98eeff" }
title   = { fg = "#98eeff" }
hovered = { fg = "#e2e5e6", bg = "#2c3334" }

# Help
[help]
on      = { fg = "#a6d98d" }
run     = { fg = "#d282d9" }
desc    = { fg = "#9ec1f3" }
hovered = { bg = "#1c2021" }
footer  = { fg = "#e2e5e6", bg = "#1c2021" }



# Filetype rules
[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#f38c61" },

	# Media
	{ mime = "{audio,video}/*", fg = "#d282d9" },

	# Archives
	{ mime = "application/*zip", fg = "#e65c68" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e65c68" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#9ec1f3" },

	# Empty files
	{ mime = "inode/x-empty", fg = "#e65c68" },

	# Special files
	{ url = "*", is = "orphan", bg = "#e65c68" },
	{ url = "*", is = "exec", fg = "#a6d98d" },

	# Fallback
	{ url = "*/", fg = "#9ec1f3" },
	{ url = "*", fg = "#e2e5e6" }
]

[icon]
globs = []
dirs  = [
	{ name = ".config", text = "" },
	{ name = ".git", text = "" },
	{ name = ".github", text = "" },
	{ name = ".npm", text = "" },
	{ name = "Desktop", text = "󱂵" },
	{ name = "Developments", text = "" },
	{ name = "Documents", text = "󱧶" },
	{ name = "Downloads", text = "󰉍" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "󱧺" },
	{ name = "Music", text = "󱍙" },
	{ name = "Pictures", text = "󰉏" },
	{ name = "Public", text = "󰉌" },
	{ name = "Templates", text = "󱞞" },
	{ name = "Videos", text = "󱞊" },
]
