#    ┏┳┓┓┏┏┓┳┳┓┏┓
#     ┃ ┣┫┣ ┃┃┃┣
#     ┻ ┛┗┗┛┛ ┗┗┛
#     Lunaris colors

# Schema
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Flavour
[flavor]
dark  = ""
light = ""

# App
[app]
overall = {}

# Manager
[mgr]
cwd = { fg = "#e8eda2", italic = true, bold = true }

# Find
find_keyword  = { fg = "#e48cc1", bg = "#dd6e6b", bold = true }
find_position = { fg = "#a7dfef", bg = "#151f26", bold = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "#87e58e", bg = "#87e58e" }
marker_cut      = { fg = "#e1837f", bg = "#e1837f" }
marker_marked   = { fg = "#e48cc1", bg = "#e48cc1" }
marker_selected = { fg = "#e8eda2", bg = "#e8eda2" }

# Count
count_copied   = { fg = "#e48cc1", bg = "#87e58e" }
count_cut      = { fg = "#e48cc1", bg = "#e1837f" }
count_selected = { fg = "#e48cc1", bg = "#d0b5f3" }

# Border
border_symbol = "│"
border_style  = { fg = "#bcf4f5" }

# Tabs
[tabs]
active   = { fg = "#e48cc1", bg = "#d0b5f3", bold = true }
inactive = { fg = "#d0b5f3", bg = "#233440" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# Mode
[mode]
normal_main = { fg = "#f6f6f5", bg = "#d0b5f3", bold = true }
normal_alt  = { fg = "#d0b5f3", bg = "#233440" }
select_main = { fg = "#f6f6f5", bg = "#e48cc1", bold = true }
select_alt  = { fg = "#f6f6f5", bg = "#233440" }
unset_main  = { fg = "#e48cc1", bg = "#d0b5f3", bold = true }
unset_alt   = { fg = "#d0b5f3", bg = "#233440" }

# Indicator
[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "█", close = "█" }

# Status bar
[status]
overall   = { fg = "#f6f6f5", bg = "#151f26" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#f6f6f5", bold = true }
progress_normal = { fg = "#baa0e8", bg = "#151f26" }
progress_error  = { fg = "#dd6e6b", bg = "#151f26" }

# Permissions
perm_type  = { fg = "#d0b5f3" }
perm_read  = { fg = "#e8eda2" }
perm_write = { fg = "#e1837f" }
perm_exec  = { fg = "#87e58e" }
perm_sep   = { fg = "#b186bf" }


# Which
[which]
cols            = 3
mask            = { bg = "#151f26" }
cand            = { fg = "#d0b5f3" }
rest            = { fg = "#d0b5f3" }
desc            = { fg = "#d0b5f3" }
separator       = " 󰶻  "
separator_style = { fg = "#e48cc1" }

# Confirm
[confirm]
border  = { fg = "#baa0e8" }
title   = { fg = "#baa0e8" }
content = {}
list    = {}
btn_yes = { bg = "#87e58e", fg = "#0e151a" }
btn_no  = { bg = "#dd6e6b", fg = "#0e151a" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#baa0e8" }
title   = { fg = "#baa0e8" }

tbl_col  = { fg = "#d0b5f3" }
tbl_cell = { fg = "#e8eda2", bg = "#151f26" }

# Notify
[notify]
title_info  = { fg = "#a7dfef" }
title_warn  = { fg = "#e8eda2" }
title_error = { fg = "#dd6e6b" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

# Picker
[pick]
border   = { fg = "#baa0e8" }
active   = { fg = "#f6f6f5", bg = "#233440" }
inactive = { fg = "#f6f6f5" }

# Input
[input]
border   = { fg = "#87e58e" }
title    = { fg = "#87e58e" }
value    = { fg = "#d0b5f3" }
selected = { bg = "#233440" }

# Completion
[cmp]
border   = { fg = "#87e58e" }
active   = { fg = "#f6f6f5", bg = "#233440" }
inactive = { fg = "#f6f6f5" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#bcf4f5" }
title   = { fg = "#bcf4f5" }
hovered = { fg = "#f6f6f5", bg = "#233440" }

# Help
[help]
on      = { fg = "#87e58e" }
run     = { fg = "#e48cc1" }
desc    = { fg = "#d0b5f3" }
hovered = { bg = "#151f26" }
footer  = { fg = "#f6f6f5", bg = "#151f26" }



# Filetype rules
[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#e8eda2" },

	# Media
	{ mime = "{audio,video}/*", fg = "#e48cc1" },

	# Archives
	{ mime = "application/*zip", fg = "#e1837f" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e1837f" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#d0b5f3" },

	# Empty files
	{ mime = "inode/x-empty", fg = "#e1837f" },

	# Special files
	{ url = "*", is = "orphan", bg = "#e1837f" },
	{ url = "*", is = "exec", fg = "#87e58e" },

	# Fallback
	{ url = "*/", fg = "#d0b5f3" },
	{ url = "*", fg = "#f6f6f5" }
]

[icon]
globs = []
dirs  = [
	{ name = ".config", text = "" },
	{ name = ".git", text = "" },
	{ name = ".github", text = "" },
	{ name = ".npm", text = "" },
	{ name = "Desktop", text = "󱂵" },
	{ name = "Developments", text = "" },
	{ name = "Documents", text = "󱧶" },
	{ name = "Downloads", text = "󰉍" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "󱧺" },
	{ name = "Music", text = "󱍙" },
	{ name = "Pictures", text = "󰉏" },
	{ name = "Public", text = "󰉌" },
	{ name = "Templates", text = "󱞞" },
	{ name = "Videos", text = "󱧺" },
	{ name = "walls", text = "󰉏" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#f6f6f5" },
	{ if = "link", text = "", fg = "#baa0e8" },
	{ if = "block", text = "", fg = "#e8eda2" },
	{ if = "char", text = "", fg = "#e8eda2" },
	{ if = "fifo", text = "", fg = "#e8eda2" },
	{ if = "sock", text = "", fg = "#e8eda2" },
	{ if = "sticky", text = "", fg = "#e8eda2" },
	{ if = "dummy", text = "", fg = "#dd6e6b" },

	# Fallback
	{ if = "dir", text = "", fg = "#d0b5f3" },
	{ if = "exec", text = "", fg = "#87e58e" },
	{ if = "!dir", text = "", fg = "#f6f6f5" },
]
