# ┏┓┏┓┳┏┳┓┏┓┏┓  ┓┏┓┳┳┓┏┳┓┏┓┳┳┓┏┓┳┳┳┓┏┓┳
# ┣ ┃ ┃ ┃  ┃┃ ━━┃┫ ┃┃┃ ┃ ┗┓┃┃┃┫ ┃┃┣┫┃┃┃
# ┻ ┗┛┻ ┻ ┗┛┗┛  ┛┗┛┻┛┗ ┻ ┗┛┗┛┛┗┛┗┛┛┗┗┛┻
# A clean, dark fcitx5 theme

[Metadata]
Name=Kintsukuroi
Version=1.0
Author=justTOBBI, Isabelinc, Kurome, Bugs
Description=Kintsukuroi colors
ScaleWithDPI=True

[InputPanel]
Font=Sans 13
Spacing=3
NormalColor=#e5c9a0
HighlightCandidateColor=#141210
HighlightColor=#c09d59
HighlightBackgroundColor=#322d28

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
Color=#322d28

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Color=#7f91b2

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
Font=Sans 10
NormalColor=#d8be97
Spacing=3

[Menu/Background]
Color=#322d28

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#c09d59
[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#141210
[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
