#    ┓ ┏┓┏┓┓┏┏┓┳┏┳┓
#    ┃ ┣┫┏┛┗┫┃┓┃ ┃
#    ┗┛┛┗┗┛┗┛┗┛┻ ┻
#

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#f38c61"
      - "bold"
    inactiveBorderColor:
      - "#95b7e6"
    searchingActiveBorderColor:
      - "#95b7e6"
      - "bold"
    optionsTextColor:
      - "#f38c61"
    selectedLineBgColor:
      - "#2c3334"
    cherryPickedCommitFgColor:
      - "#d95762"
    cherryPickedCommitBgColor:
      - "#4B2024"
    markedBaseCommitFgColor:
      - "#9ec1f3"
    markedBaseCommitBgColor:
      - "#ff9366"
    unstagedChangesColor:
      - "#d95762"
    defaultFgColor:
      - "#e2e5e6"
