#    ┓ ┏┓┏┓┓┏┏┓┳┏┳┓
#    ┃ ┣┫┏┛┗┫┃┓┃ ┃
#    ┗┛┛┗┗┛┗┛┗┛┻ ┻
#

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#e8eda2"
      - "bold"
    inactiveBorderColor:
      - "#baa0e8"
    searchingActiveBorderColor:
      - "#baa0e8"
      - "bold"
    optionsTextColor:
      - "#e8eda2"
    selectedLineBgColor:
      - "#233440"
    cherryPickedCommitFgColor:
      - "#dd6e6b"
    cherryPickedCommitBgColor:
      - "#4d292a"
    markedBaseCommitFgColor:
      - "#d0b5f3"
    markedBaseCommitBgColor:
      - "#3d3750"
    unstagedChangesColor:
      - "#dd6e6b"
    defaultFgColor:
      - "#f6f6f5"
