#    ┓ ┏┓┏┓┓┏┏┓┳┏┳┓
#    ┃ ┣┫┏┛┗┫┃┓┃ ┃
#    ┗┛┛┗┗┛┗┛┗┛┻ ┻
#

gui:
  border: single
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#c09d59"
      - "bold"
    inactiveBorderColor:
      - "#7f91b2"
    searchingActiveBorderColor:
      - "#7f91b2"
      - "bold"
    optionsTextColor:
      - "#c09d59"
    selectedLineBgColor:
      - "#4d463e"
    cherryPickedCommitFgColor:
      - "#c06c5c"
    cherryPickedCommitBgColor:
      - "#4b2a24"
    markedBaseCommitFgColor:
      - "#a3a9ce"
    markedBaseCommitBgColor:
      - "#373844"
    unstagedChangesColor:
      - "#c06c5c"
    defaultFgColor:
      - "#e5c9a0"
