#  ┓┏┓┏┏┓┳┓┓ ┏┓┏┓┓┏┓
#  ┣┫┗┫┃┃┣┫┃ ┃┃┃ ┃┫
#  ┛┗┗┛┣┛┛┗┗┛┗┛┗┛┛┗┛
#

# Colors
$text_color = rgba(e2e5e6ff)
$text_color_clock = rgba(95b7e6ff)
$text_color_status = rgba(e57474ff)
$entry_background_color = rgba(10131480)
$entry_border_color = rgba(e2e5e6d3)
$entry_color = rgba(e2e5e6d3)
$entry_check_color = rgba(a6d98dff)
$entry_error_color = rgba(d95762ff)
$capslock_color = rgba(d95762ff)
$numlock_color = rgba(e2e5e6d3)
$bothlock_color = rgba(d95762ff)

# Fonts
$font_family = GeistMono Nerd Font Propo
$font_family_clock_date = Lilex

# Image
$image = $HOME/.local/share/hyprlock_bg

# General
general {
    grace = 1
    hide_cursor = true
    immediate_render = true
}

# Animations
animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 5, linear
}

# Background
background {
    path = $image
    blur_size = 4
    blur_passes = 3
}

# Input Field
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    rounding = 0
    dots_size = 0.1
    dots_spacing = 0.3
    dots_rounding = 0
    font_family = $font_family
    placeholder_text = Enter Password 󰌾
    fail_text = <i>$PAMFAIL ($ATTEMPTS)</i>
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    check_color = $entry_check_color
    fail_color = $entry_error_color
    font_color = $entry_color
    capslock_color = $capslock_color
    numlock_color = $numlock_color
    bothlock_color = $bothlock_color
    fade_on_empty = true
    position = 0, 10
    halign = center
    valign = center
}

label { # Caps Lock Warning
    monitor =
    text = cmd[update:250] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/check-capslock.sh
    color = $capslock_color
    font_size = 16
    font_family = $font_family
    position = 0, -40
    halign = center
    valign = center
}

label { # Hours
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $text_color_clock
    font_size = 112
    font_family = $font_family_clock_date
    shadow_passes = 3
    shadow_size = 4
    position = 0, -40
    halign = center
    valign = top
}

label { # Minutes
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $text_color_clock
    font_size = 112
    font_family = $font_family_clock_date
    shadow_passes = 3
    shadow_size = 4
    position = 0, -180
    halign = center
    valign = top
}


label { # Today
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $text_color
    font_size = 30
    font_family = $font_family_clock_date
    position = 0, -345
    halign = center
    valign = top
}

label { # Week
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $text_color
    font_size = 25
    font_family = $font_family_clock_date
    position = 0, -395
    halign = center
    valign = top
}

label { # Weather
    monitor =
    text = cmd[update:18000000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/weather.sh
    color = $text_color
    font_size = 18
    font_family = $font_family
    position = 0, 40
    halign = center
    valign = bottom
}


label { # Status
    monitor =
    text = cmd[update:5000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/status.sh
    color = $text_color_status
    font_size = 14
    font_family = $font_family
    position = 30, -30
    halign = left
    valign = top
}
