# ┓┏┓┏┏┓┳┓┏┓┏┳┓┏┓┏┓┳┓┏┓┳┳┓┏┓
# ┣┫┗┫┃┃┣┫┃┃ ┃ ┣┓┣ ┃┃┃┓┃┃┃┣
# ┛┗┗┛┣┛┛┗┗┻ ┻ ┗┛┗┛┛┗┗┛┻┛┗┗┛
#

theme {
    color_scheme = /home/bugs/.local/share/color-schemes/EF-DREAM.colors
    icon_theme = Papirus-Dark
    style = kvantum-dark
    font_fixed = Space Mono
    font_fixed_size = 11
    font = Aporetic Sans
    font_size = 11
}

misc {
    single_click_activate = true
    menus_have_icons = true
    shortcuts_for_context_menus = true
}
