# ┏┓┳┳┓┏┓┏┓┏┓
# ┣ ┃┃┃┣┫┃ ┗┓
# ┗┛┛ ┗┛┗┗┛┗┛
#

#--------------emacs-------------------#
#--------------------------------------#
windowrule = tag +emacs, match:class (Emacs|emacs|emacs-client|emacsclient)
windowrule = match:tag emacs, opacity 1.0 0.95
