# ┏┓┳┓ ┏┓  ┳┳┓┏┓┳┓┏┓┏┓┏┓┳┓┏┓
# ┣ ┃┃ ┣ ━━┃┃┃┣┫┃┃┣┫┃┓┣ ┣┫┗┓
# ┻ ┻┗┛┗┛  ┛ ┗┛┗┛┗┛┗┗┛┗┛┛┗┗┛
#

#------------file manger window rules---------------#
#---------------------------------------------------#
windowrule = match:class ^(org.gnome.Nautilus)$, opacity 0.98 0.95
