# ┏┓┳┓┏┓
# ┃┃┣┫┗┓
# ┗┛┻┛┗┛
#

#--------------OBS Studio--------------------#
#--------------------------------------------#
windowrule = tag +obs-studio, match:class (com.obsproject.Studio)
windowrule = match:tag obs-studio, opacity 1.0 1.0, fullscreen on
