#    ┏┓┓┏┏┓┏┳┓┏┓┳┳┓
#    ┗┓┗┫┗┓ ┃ ┣ ┃┃┃
#    ┗┛┗┛┗┛ ┻ ┗┛┛ ┗
#

windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 875 600, tag:floating-window

# Floating window tag
windowrule = tag +floating-window, class:(com.gabm.satty|About|swayimg|thunara|blueman-manager|nwg-look)

# File dialogs
windowrule = tag +floating-window, class:(xdg-desktop-portal-gtk|DesktopEditors|thunar), title:^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)
windowrule = float, class:org.gnome.Calculator

# Media windows (no transparency)
windowrule = opacity 1 1, class:^(zoom|vlc|com.obsproject.Studio|swayimg)$

# Popped window rounding
windowrule = rounding 8, tag:pop

