# ┏┳┓┏┓┳┓┳┳┓┳┳┓┏┓┓ ┏┓
#  ┃ ┣ ┣┫┃┃┃┃┃┃┣┫┃ ┗┓
#  ┻ ┗┛┛┗┛ ┗┻┛┗┛┗┗┛┗┛
# 

#--------------terminals-------------------#
#------------------------------------------#
windowrule = tag +terminal, match:class (Alacritty|kitty|com.mitchellh.ghostty)
windowrule = match:tag terminal, opacity 0.98 0.95
