# ┓┏┳┳┓  ┳┳┓┏┓┳┓┏┓┏┓┏┓┳┓┏┓
# ┃┃┃┃┃━━┃┃┃┣┫┃┃┣┫┃┓┣ ┣┫┗┓
# ┗┛┛ ┗  ┛ ┗┛┗┛┗┛┗┗┛┗┛┛┗┗┛
# 

#--------------vm managers-------------------#
#--------------------------------------------#
windowrule = tag +vm-managers, match:class (virt-viewer|virt-manager|qemu)
windowrule = match:tag vm-managers, opacity 1.0 1.0, fullscreen on
