#    ┳┳┓┏┓┓┏
#    ┃┃┃┃┃┃┃
#    ┛ ┗┣┛┗┛
#

# Main mpv theme options
background-color='#101314'
osd-back-color='#1c2021'
osd-border-color='#1c2021'
osd-color='#95b7e6'
osd-shadow-color='#101314'

# OSD font
osd-font=Lilex Bold
osd-font-size=28

# Subtitles
sub-font=Noto Sans
sub-font-size=36
sub-bold=yes
sub-border-size=2
sub-border-color=0.0/0.0/0.0/1.0
sub-shadow-offset=1
sub-shadow-color=0.0/0.0/0.0/0.6
sub-ass-style-overrides=Kerning=yes
