#    ┳┳┓┏┓┓┏
#    ┃┃┃┃┃┃┃
#    ┛ ┗┣┛┗┛
#

# Main mpv theme options
background-color='#141210'
osd-back-color='#322d28'
osd-border-color='#322d28'
osd-color='#7f91b2'
osd-shadow-color='#141210'


# OSD font
osd-font=JetBrains Mono
osd-font-size=28

# Subtitles
sub-font=Noto Sans
sub-font-size=36
sub-bold=yes
sub-border-size=2
sub-border-color=0.0/0.0/0.0/1.0
sub-shadow-offset=1
sub-shadow-color=0.0/0.0/0.0/0.6
sub-ass-style-overrides=Kerning=yes
