#    ┳┳┓┏┓┓┏
#    ┃┃┃┃┃┃┃
#    ┛ ┗┣┛┗┛
#

# Main mpv theme options
background-color='#232025'
osd-back-color='#322f34'
osd-border-color='#322f34'
osd-color='#57b0ff'
osd-shadow-color='#232025'


# OSD font
osd-font=Space Mono
osd-font-size=28

# Subtitles
sub-font=Noto Sans
sub-font-size=36
sub-bold=yes
sub-border-size=2
sub-border-color=0.0/0.0/0.0/1.0
sub-shadow-offset=1
sub-shadow-color=0.0/0.0/0.0/0.6
sub-ass-style-overrides=Kerning=yes

# Misc options
watch-later-options-remove=sub-pos
