# ┏┓┏┓┳┏┳┓┏┓┏┓┏━  ┏┓┏┓  ┳┓┳┓┏┓┏┓┳┳┓
# ┣ ┃ ┃ ┃  ┃┃ ┗┓━━┣ ┣ ━━┃┃┣┫┣ ┣┫┃┃┃
# ┻ ┗┛┻ ┻ ┗┛┗┛┗┛  ┗┛┻   ┻┛┛┗┗┛┛┗┛ ┗
#
# A clean, dreamy fcitx5 theme

[Metadata]
Name=EF-DREAM
Version=1.0
Author=justTOBBI, Isabelinc, Kurome, Bugs
Description=Kintsukuroi colors
ScaleWithDPI=True

[InputPanel]
Font=Sans 13
Spacing=3
NormalColor=#efd5c5
HighlightCandidateColor=#232025
HighlightColor=#ffaacf
HighlightBackgroundColor=#322f34

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
Color=#322f34

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Color=#ffaacf

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8
[Menu]
Font=Sans 10
NormalColor=#8f8886
Spacing=3

[Menu/Background]
Color=#322f34
[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#ffaacf

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#232025

[Menu/CheckBox]
Image=radio.png
[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
