# ┓┏┓┳┳┓┏┳┓┏┓┳┳┓┏┓┳┳┳┓┏┓┳
# ┃┫ ┃┃┃ ┃ ┗┓┃┃┃┫ ┃┃┣┫┃┃┃
# ┛┗┛┻┛┗ ┻ ┗┛┗┛┛┗┛┗┛┛┗┗┛┻
#
#
# Theme: Kintsukuroi
# By: bugs
theme[main_bg]="#141210"
theme[main_fg]="#e5c9a0"
# Title color for boxes
theme[title]="#e5c9a0"
# Highlight color for keyboard shortcuts
theme[hi_fg]="#c09d59"
# Selected item in processes box
theme[selected_bg]="#4d463e"
theme[selected_fg]="#a3a9ce"
# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a3a9ce"
# Cpu box outline color
theme[cpu_box]="#7b9695"
# Memory/disks box outline color
theme[mem_box]="#7b9695"
# Net up/down box outline color
theme[net_box]="#7b9695"
# Processes box outline color
theme[proc_box]="#7b9695"
# Box divider line and small boxes line color
theme[div_line]="#7b9695"
# Temperature graph colors
theme[temp_start]="#78997a"
theme[temp_mid]="#c09d59"
theme[temp_end]="#c06c5c"
# CPU graph colors
theme[cpu_start]="#78997a"
theme[cpu_mid]="#c09d59"
theme[cpu_end]="#c06c5c"
# Mem/Disk free meter
theme[free_start]="#78997a"
theme[free_mid]="#c09d59"
theme[free_end]="#c06c5c"
# Mem/Disk cached meter
theme[cached_start]="#78997a"
theme[cached_mid]="#c09d59"
theme[cached_end]="#c06c5c"
# Mem/Disk available meter
theme[available_start]="#78997a"
theme[available_mid]="#c09d59"
theme[available_end]="#c06c5c"
# Mem/Disk used meter
theme[used_start]="#78997a"
theme[used_mid]="#c09d59"
theme[used_end]="#c06c5c"
# Download graph colors
theme[download_start]="#78997a"
theme[download_mid]="#c09d59"
theme[download_end]="#c06c5c"
# Upload graph colors
theme[upload_start]="#78997a"
theme[upload_mid]="#c09d59"
theme[upload_end]="#c06c5c"
