# ┳┓┏┓┏┓┳
# ┃┃┣┫┃┓┃
# ┛┗┛┗┗┛┻
# Theme: Nagi
# By: bugs

theme[main_bg]="#101314"
theme[main_fg]="#e2e5e6"

# Title color for boxes
theme[title]="#e2e5e6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#f38c61"

# Selected item in processes box
theme[selected_bg]="#2c3334"
theme[selected_fg]="#9ec1f3"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#9ec1f3"

# Cpu box outline color
theme[cpu_box]="#92e2f2"

# Memory/disks box outline color
theme[mem_box]="#92e2f2"

# Net up/down box outline color
theme[net_box]="#92e2f2"

# Processes box outline color
theme[proc_box]="#92e2f2"

# Box divider line and small boxes line color
theme[div_line]="#92e2f2"

# Temperature graph colors
theme[temp_start]="#a6d98d"
theme[temp_mid]="#f38c61"
theme[temp_end]="#d95762"

# CPU graph colors
theme[cpu_start]="#a6d98d"
theme[cpu_mid]="#f38c61"
theme[cpu_end]="#d95762"

# Mem/Disk free meter
theme[free_start]="#a6d98d"
theme[free_mid]="#f38c61"
theme[free_end]="#d95762"

# Mem/Disk cached meter
theme[cached_start]="#a6d98d"
theme[cached_mid]="#f38c61"
theme[cached_end]="#d95762"

# Mem/Disk available meter
theme[available_start]="#a6d98d"
theme[available_mid]="#f38c61"
theme[available_end]="#d95762"

# Mem/Disk used meter
theme[used_start]="#a6d98d"
theme[used_mid]="#f38c61"
theme[used_end]="#d95762"

# Download graph colors
theme[download_start]="#a6d98d"
theme[download_mid]="#f38c61"
theme[download_end]="#d95762"

# Upload graph colors
theme[upload_start]="#a6d98d"
theme[upload_mid]="#f38c61"
theme[upload_end]="#d95762"
