#  ┳┓┏┓┏┓┏┓┳┓┏┓┏┳┓┳┏┓┳┓┏┓
#  ┃┃┣ ┃ ┃┃┣┫┣┫ ┃ ┃┃┃┃┃┗┓
#  ┻┛┗┛┗┛┗┛┛┗┛┗ ┻ ┻┗┛┛┗┗┛
#

#---------general---------#
#-------------------------#
general {
    gaps_in = 10
    gaps_out = 10
    gaps_workspaces = 50
    border_size = 1
    col.active_border = rgba(7AA2F7FF)
    col.inactive_border = rgba(292E42FF)
    resize_on_border = true
    no_focus_fallback = true
    allow_tearing = true
    snap {
    	enabled = true
    }
    layout = dwindle
}

#---------decoration---------#
#----------------------------#
decoration {
    rounding = 0
    blur {
        enabled = true
        xray = true
        special = false
        new_optimizations = true
        size = 3
        passes = 1
        brightness = 1
        noise = 0.01
        contrast = 1
        vibrancy = 0.1696
        popups = true
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }
    shadow {
        enabled = true
        ignore_window = true
        range = 18
        offset = 2, 2
        render_power = 3
        color = rgba(1A1B26FF)
    }
    dim_inactive = true
    dim_strength = 0.025
    dim_special = 0.07
}

#---------group & groupbar---------#
#----------------------------------#

group {
    col.border_active = rgba(7AA2F7FF)
    col.border_inactive = rgba(292E42FF)
    col.border_locked_active = rgba(FF9E64FF)
    col.border_locked_inactive = rgba(292E42FF)
    groupbar {
      enabled = true
      gradients = 1
      render_titles = true
      font_family = GeistMono Nerd Font
      font_size = 14
      font_weight_inactive = normal
      font_weight_active = semibold
      height = 40
      col.active = rgba(292E42FF)
      col.inactive = rgba(1A1B26FF)
      col.locked_active = rgba(1ABC9CFF)
      col.locked_inactive = rgba(292E42FF)
      text_offset = 0
      text_color = rgba(C0CAF5FF)
      text_color_inactive = rgba(292E42FF)
    }
}
