#  ┳┓┏┓┏┓┏┓┳┓┏┓┏┳┓┳┏┓┳┓┏┓
#  ┃┃┣ ┃ ┃┃┣┫┣┫ ┃ ┃┃┃┃┃┗┓
#  ┻┛┗┛┗┛┗┛┛┗┛┗ ┻ ┻┗┛┛┗┗┛
#

#---------general---------#
#-------------------------#
general {
    gaps_in = 10
    gaps_out = 10
    gaps_workspaces = 50
    border_size = 1
    col.active_border = rgba(e5c9a0ff)
    col.inactive_border = rgba(322d28ff)
    resize_on_border = true
    no_focus_fallback = true
    allow_tearing = true
    snap {
    	enabled = true
    }
    layout = dwindle
}
#---------decoration---------#
#----------------------------#
decoration {
    rounding = 0
    blur {
        enabled = true
        xray = true
        special = false
        new_optimizations = true
        size = 3
        passes = 1
        brightness = 1
        noise = 0.01
        contrast = 1
        vibrancy = 0.1696
        popups = true
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }
    shadow {
        enabled = true
        ignore_window = true
        range = 18
        offset = 2, 2
        render_power = 3
        color = rgba(000000d3)
    }
    dim_inactive = true
    dim_strength = 0.025
    dim_special = 0.07
}
#---------group & groupbar---------#
#----------------------------------#
group {
    col.border_active = rgba(e5c9a0ff)
    col.border_inactive = rgba(4d463eff)
    col.border_locked_active = rgba(c09d59ff)
    col.border_locked_inactive = rgba(4d463eff)
    groupbar {
      enabled = true
      gradients = 1
      render_titles = true
      font_family = Intel One Mono
      font_size = 14
      font_weight_inactive = normal
      font_weight_active = semibold
      height = 40
      col.active = rgba(322d28ff)
      col.inactive = rgba(141210ff)
      col.locked_active = rgba(c09d59ff)
      col.locked_inactive = rgba(4d463eff)
      text_offset = 0
      text_color = rgba(e5c9a0ff)
      text_color_inactive = rgba(d8be97ff)
      gaps_in = 0
      gaps_out = 0
    }
}
