
#  ┓ ┏┓┓┏┏┓┳┓  ┳┓┳┳┓ ┏┓┏┓
#  ┃ ┣┫┗┫┣ ┣┫  ┣┫┃┃┃ ┣ ┗┓
#  ┗┛┛┗┗┛┗┛┛┗  ┛┗┗┛┗┛┗┛┗┛
#                        

#---------xray--------------#
#---------------------------#
layerrule {
  name = layerrule-xray
  xray = 1
  match:namespace = .*
}


#-----------waybar-------------#
#------------------------------#
layerrule {
  name = layerrule-waybar
  blur = on
  ignore_alpha = 0.5
  match:namespace = waybar
}


#-----------mako notification window-------------#
#------------------------------------------------#
layerrule {
  name = layerrule-mako-notification-window
  blur = on
  ignore_alpha = 0.5
  xray = 0
  match:namespace = notifications
}

#-------------rofi--------------#
#-------------------------------#
layerrule {
  name = layerrule-rofi
  blur = on
  ignore_alpha = 0
  xray = 0
  no_anim = on
  match:namespace = rofi
}
