
#  ┓ ┏┓┓┏┏┓┳┓  ┳┓┳┳┓ ┏┓┏┓
#  ┃ ┣┫┗┫┣ ┣┫  ┣┫┃┃┃ ┣ ┗┓
#  ┗┛┛┗┗┛┗┛┛┗  ┛┗┗┛┗┛┗┛┗┛
#                        

#---------xray--------------#
#---------------------------#
layerrule {
  name = layerrule-xray
  xray = 1
  match:namespace = .*
}


#-----------waybar-------------#
#------------------------------#
layerrule {
  name = layerrule-waybar
  blur = on
  ignore_alpha = 0.5
  match:namespace = waybar
}


#-----------swaync-------------#
#------------------------------#
layerrule {
  name = layerrule-swaync-control-center
  blur = on
  ignore_alpha = 0.5
  xray = 0
  match:namespace = swaync-control-center
}

layerrule {
  name = layerrule-swaync-notification-window
  blur = on
  ignore_alpha = 0.5
  xray = 0
  match:namespace = swaync-notification-window
}


#-----------swayosd-------------#
#-------------------------------#
layerrule {
  name = layerrule-swayosd
  blur = on
  ignore_alpha = 0.5
  xray = 0
  match:namespace = swayosd
}


#-------------rofi--------------#
#-------------------------------#
layerrule {
  name = layerrule-rofi
  blur = on
  ignore_alpha = 0
  xray = 0
  no_anim = on
  match:namespace = rofi
}
