#  ┓ ┏┓┓┏┏┓┳┓  ┳┓┳┳┓ ┏┓┏┓
#  ┃ ┣┫┗┫┣ ┣┫  ┣┫┃┃┃ ┣ ┗┓
#  ┗┛┛┗┗┛┗┛┛┗  ┛┗┗┛┗┛┗┛┗┛
#                        

#--------------xray layer-------------------#
#------------------------------------------#
layerrule {
    name = xray-all
    match:namespace = .*
    xray = 1
}

#--------------waybar layer----------------#
#------------------------------------------#
layerrule {
    name = waybar-layer
    match:namespace = waybar
    blur = on
    ignore_alpha = 0.5
    no_anim = on
}

#--------swaync control center layer-------#
#------------------------------------------#
layerrule {
    name = swaync-control-layer
    match:namespace = swaync-control-center
    blur = on
    ignore_alpha = 0.5
    xray = 0
}

#----------swaync notification layer--------#
#-------------------------------------------#
layerrule {
    name = swaync-notification-layer
    match:namespace = swaync-notification-window
    blur = on
    ignore_alpha = 0.5
    xray = 0
}

#--------------swayosd layer----------------#
#-------------------------------------------#

layerrule {
    name = swayosd-layer
    match:namespace = swayosd
    blur = on
    ignore_alpha = 0.5
    xray = 0
}

#--------------rofi layer-------------------#
#-------------------------------------------#

layerrule {
    name = rofi-layer
    match:namespace = rofi
    blur = on
    xray = 0
    no_anim = off
}
