# ┏┓┳┓┏┓┏┓┳┓┏┓┳┳┓┏┓
# ┃┃┣┫┃┃┃┓┣┫┣┫┃┃┃┗┓
# ┣┛┛┗┗┛┗┛┛┗┛┗┛ ┗┗┛

$terminal = ghostty
$fileManager = thunar
$browser = chromium
$volumecontrol = hyprctl dispatch exec '[float on; center on] $terminal -e wiremix'
$recordingApplication = obs
$appLauncher = rofi -show drun -theme $HOME/.config/rofi/launcher-3.rasi
$windowSwitcher = rofi -show window -theme $HOME/.config/rofi/windowSwitcher.rasi

