# ┏┓┳┓┏┓┏┓┳┓┏┓┳┳┓┏┓
# ┃┃┣┫┃┃┃┓┣┫┣┫┃┃┃┗┓
# ┣┛┛┗┗┛┗┛┛┗┛┗┛ ┗┗┛

$terminal = ghostty
$editor = emacsclient -c -a ""
$fileManager = nautilus
$browser = chromium
$volumecontrol = hyprctl dispatch exec '[float on; center on] $terminal --adjust-cell-height=0% -e wiremix'
$processmonitor = hyprctl dispatch exec '[float on; center on] $terminal --adjust-cell-height=0% -e btop'
$recordingApplication = obs
$appLauncher = rofi -show drun -theme $HOME/.config/rofi/launcher-2.rasi
