# ┏┓┳┓┏┓┏┓┳┓┏┓┳┳┓┏┓
# ┃┃┣┫┃┃┃┓┣┫┣┫┃┃┃┗┓
# ┣┛┛┗┗┛┗┛┛┗┛┗┛ ┗┗┛

$terminal = $TERMINAL
$fileManager = thunar
$browser = chromium
$volumecontrol = hyprctl dispatch exec '[float] $TERMINAL -e wiremix'
$recordingApplication = obs

