#  ┓ ┏┳┳┓┳┓┏┓┓ ┏  ┳┓┳┳┓ ┏┓┏┓
#  ┃┃┃┃┃┃┃┃┃┃┃┃┃  ┣┫┃┃┃ ┣ ┗┓
#  ┗┻┛┻┛┗┻┛┗┛┗┻┛  ┛┗┗┛┗┛┗┛┗┛
#

#------------source all modularized window rules---------------------#
#--------------------------------------------------------------------#
source = ~/.config/hypr/modules/windowrules/general.conf
source = ~/.config/hypr/modules/windowrules/system.conf
source = ~/.config/hypr/modules/windowrules/browsers.conf
source = ~/.config/hypr/modules/windowrules/filemanagers.conf
source = ~/.config/hypr/modules/windowrules/zathura.conf
source = ~/.config/hypr/modules/windowrules/vm-managers.conf
source = ~/.config/hypr/modules/windowrules/terminals.conf
source = ~/.config/hypr/modules/windowrules/emacs.conf
source = ~/.config/hypr/modules/windowrules/picInPic.conf
