#  ┓ ┏┏┓┳┓┓┏┓┏┓┏┓┏┓┏┓┏┓┳┓┳┳┓ ┏┓┏┓
#  ┃┃┃┃┃┣┫┃┫ ┗┓┃┃┣┫┃ ┣ ┣┫┃┃┃ ┣ ┗┓
#  ┗┻┛┗┛┛┗┛┗┛┗┛┣┛┛┗┗┛┗┛┛┗┗┛┗┛┗┛┗┛
#



# You can set workspace rules to achieve workspace-specific behaviors.
# For instance, you can define a workspace where all windows are drawn without borders or gaps.

# https://wiki.hypr.land/Configuring/Workspace-Rules/

# To replicate “smart gaps” / “no gaps when only” from other WMs/Compositors, use this bad boy
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = border_size 0, match:float 0, match:workspace w[tv1]
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]
# windowrule = border_size 0, match:float 0, match:workspace f[1]
# windowrule = rounding 0, match:float 0, match:workspace f[1]

# More rules
# workspace = 3, rounding:false, decorate:false
# workspace = name:coding, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, monitor:DP-1
# workspace = 8,bordersize:8
# workspace = name:Hello, monitor:DP-1, default:true
# workspace = name:gaming, monitor:desc:Chimei Innolux Corporation 0x150C, default:true
# workspace = 5, on-created-empty:[float] chromium
# workspace = special:scratchpad, on-created-empty:ghostty
