[buildPlans.IosevkaNagi]
family = "IosevkaNagi"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaNagi.variants]
  inherits = "ss07"

    [buildPlans.IosevkaNagi.variants.design]
    three = "flat-top-serifless"
    five = "upright-flat-serifless"
    six = "open-contour"
    seven = "straight-serifless-crossbar"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "tall-reverse-slashed"
    capital-a = "curly-serifless"
    capital-b = "standard-interrupted-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-k = "curly-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "straight-serifless-with-horizontal-crossbar"
    a = "single-storey-serifless"
    b = "bottom-cut-serifless"
    c = "serifless"
    d = "toothed-serifless"
    e = "flat-crossbar"
    f = "serifless-crossbar-at-x-height"
    g = "double-storey"
    i = "serifed-flat-tailed"
    k = "cursive-serifless"
    l = "hooky"
    q = "straight-serifless"
    r = "corner-hooked-serifless"
    s = "serifless"
    t = "bent-hook"
    u = "tailed-serifless"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "curly-serifless"
    z = "straight-serifless-with-horizontal-crossbar"
    number-sign = "upright"
    percent = "rings-continuous-slash-also-connected"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

    [buildPlans.IosevkaNagi.variants.italic]
    three = "flat-top-serifless"
    five = "upright-flat-serifless"
    six = "open-contour"
    seven = "straight-serifless-crossbar"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "tall-reverse-slashed"
    capital-a = "curly-serifless"
    capital-b = "standard-interrupted-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-k = "curly-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "straight-serifless-with-horizontal-crossbar"
    a = "single-storey-serifless"
    b = "bottom-cut-serifless"
    c = "serifless"
    d = "toothed-serifless"
    e = "flat-crossbar"
    f = "serifless-crossbar-at-x-height"
    g = "double-storey"
    i = "serifed-flat-tailed"
    k = "cursive-serifless"
    l = "hooky"
    q = "straight-serifless"
    r = "corner-hooked-serifless"
    s = "serifless"
    t = "bent-hook"
    u = "tailed-serifless"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "curly-serifless"
    z = "straight-serifless-with-horizontal-crossbar"
    number-sign = "upright"
    percent = "rings-continuous-slash-also-connected"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

    [buildPlans.IosevkaNagi.variants.oblique]
    three = "flat-top-serifless"
    five = "upright-flat-serifless"
    six = "open-contour"
    seven = "straight-serifless-crossbar"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "tall-reverse-slashed"
    capital-a = "curly-serifless"
    capital-b = "standard-interrupted-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-k = "curly-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "straight-serifless-with-horizontal-crossbar"
    a = "single-storey-serifless"
    b = "bottom-cut-serifless"
    c = "serifless"
    d = "toothed-serifless"
    e = "flat-crossbar"
    f = "serifless-crossbar-at-x-height"
    g = "double-storey"
    i = "serifed-flat-tailed"
    k = "cursive-serifless"
    l = "hooky"
    q = "straight-serifless"
    r = "corner-hooked-serifless"
    s = "serifless"
    t = "bent-hook"
    u = "tailed-serifless"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "curly-serifless"
    z = "straight-serifless-with-horizontal-crossbar"
    number-sign = "upright"
    percent = "rings-continuous-slash-also-connected"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

  [buildPlans.IosevkaNagi.ligations]
  inherits = "dlig"

[buildPlans.IosevkaNagi.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaNagi.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaNagi.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaNagi.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaNagi.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaNagi.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaNagi.widths.Extended]
shape = 720
menu = 7
css = "expanded"
