; My custom theme for fast-syntax-highlighting

[base]
default          = none
unknown-token    = 9,bold
commandseparator = none
redirection      = none
here-string-tri  = 11
here-string-text = 18
here-string-var  = 14,bg:18
exec-descriptor  = 11,bold
comment          = 8,bold
correct-subtle   = 12
incorrect-subtle = 10
subtle-separator = 10
subtle-bg        = bg:18
secondary        = free

[command-point]
reserved-word  = 11
subcommand     = 11
alias          = 10
suffix-alias   = 10
global-alias   = bg:blue
builtin        = 10
function       = 10
command        = 10
precommand     = 10
hashed-command = 10
single-sq-bracket = 10
double-sq-bracket = 10
double-paren   = 11

[paths]
path          = 13
pathseparator = 13
path-to-dir   = 13,underline
globbing      = 12,bold
globbing-ext  = 13

[brackets]
paired-bracket = 11,bg:8
bracket-level-1 = 10,bold
bracket-level-2 = 11,bold
bracket-level-3 = 14,bold

[arguments]
single-hyphen-option   = 14
double-hyphen-option   = 14
back-quoted-argument   = none
single-quoted-argument = 11
double-quoted-argument = 11
dollar-quoted-argument = 11

[in-string]
back-dollar-quoted-argument           = 14
back-or-dollar-double-quoted-argument = 14

[other]
variable             = 10,bold
assign               = none
assign-array-bracket = 10
history-expansion    = 12,bold

[math]
mathvar = 12,bold
mathnum = 13
matherr = 10

[for-loop]
forvar = none
fornum = 13
foroper = 11
forsep = 11,bold

[case]
case-input       = 10
case-parentheses = 11
case-condition   = bg:blue
