# ┏┓┏┓┳┏┳┓┏┓┏┓┏━  ┏┓┓┏┏┓┳┓┳┓┓ ┳┳┏┓┓┏
# ┣ ┃ ┃ ┃  ┃┃ ┗┓━━┣ ┃┃┣ ┣┫┣┫┃ ┃┃┗┓┣┫
# ┻ ┗┛┻ ┻ ┗┛┗┛┗┛  ┗┛┗┛┗┛┛┗┻┛┗┛┗┛┗┛┛┗
#
# A everblush fcitx5 theme

[Metadata]
Name=Everblush
Version=1.0
Author=justTOBBI, Isabelinc, Kurome
Description=Tokyo Night Color Theme
ScaleWithDPI=True

[InputPanel]
Font=Sans 13
Spacing=3
NormalColor=#dadada
HighlightCandidateColor=#141b1e
HighlightColor=#67b0e8
HighlightBackgroundColor=#232a2d

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
Color=#232a2d

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Color=#67b0e8

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
Font=Sans 10
NormalColor=#dadada
Spacing=3

[Menu/Background]
Color=#232a2d

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#c47fd5

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#141b1e

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
