# ┏┓┏┓┳┏┳┓┏┓┏┓┏━  ┏┓┓┏┏┓┳┓┳┓┓ ┳┳┏┓┓┏
# ┣ ┃ ┃ ┃  ┃┃ ┗┓━━┣ ┃┃┣ ┣┫┣┫┃ ┃┃┗┓┣┫
# ┻ ┗┛┻ ┻ ┗┛┗┛┗┛  ┗┛┗┛┗┛┛┗┻┛┗┛┗┛┗┛┛┗
#
# A clean, dark fcitx5 theme

[Metadata]
Name=Lunaris
Version=1.0
Author=justTOBBI, Isabelinc, Kurome, Bugs
Description=Nagi color palette
ScaleWithDPI=True

[InputPanel]
Font=Sans 13
Spacing=3
NormalColor=#f6f6f5
HighlightCandidateColor=#0e151a
HighlightColor=#e8eda2
HighlightBackgroundColor=#151f26

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
Color=#151f26

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Color=#baa0e8

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
Font=Sans 10
NormalColor=#e6e6e5
Spacing=3

[Menu/Background]
Color=#151f26

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#e8eda2

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#0e151a

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
