# ┏┓┏┓┳┏┳┓┏┓┏┓┏━  ┏┓┓┏┏┓┳┓┳┓┓ ┳┳┏┓┓┏
# ┣ ┃ ┃ ┃  ┃┃ ┗┓━━┣ ┃┃┣ ┣┫┣┫┃ ┃┃┗┓┣┫
# ┻ ┗┛┻ ┻ ┗┛┗┛┗┛  ┗┛┗┛┗┛┛┗┻┛┗┛┗┛┗┛┛┗
#
# A clean, dark fcitx5 theme

[Metadata]
Name=Nagi
Version=1.0
Author=justTOBBI, Isabelinc, Kurome, Bugs
Description=Nagi color palette
ScaleWithDPI=True

[InputPanel]
Font=Sans 13
Spacing=3
NormalColor=#dadada
HighlightCandidateColor=#101314
HighlightColor=#95b7e6
HighlightBackgroundColor=#1c2021

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
Color=#1c2021

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Color=#95B7E6

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
Font=Sans 10
NormalColor=#e2e5e6
Spacing=3

[Menu/Background]
Color=#1c2021

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#f38c61

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#101314

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
